/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kA7EBXgYPON
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardContent } from "@/components/ui/card"

export function ProfilePage() {
  return (
    <main className="mx-auto max-w-[400px] p-4 space-y-8">
      <section className="flex items-center space-x-4">
        <Avatar className="h-24 w-24">
          <AvatarImage src="/placeholder-user.jpg" alt="User name" />
        </Avatar>
        <div className="space-y-2">
          <h1 className="text-2xl text-white font-bold">User Name</h1>
          <p className="text-white">user@example.com</p>
          <Button className="w-full">Contact</Button>
        </div>
      </section>
      <Tabs defaultValue="about" className="w-full">
        <TabsList className="flex space-x-4">
          <TabsTrigger value="about">Diterima</TabsTrigger>
          <TabsTrigger value="photos">Dicuci</TabsTrigger>
          <TabsTrigger value="posts">Selesai</TabsTrigger>
        </TabsList>
        <TabsContent value="about">
        <h2 className="text-lg text-white font-bold my-5">Yang sudah diterima</h2>
          <Card>
            <CardContent>
              <h2 className="text-lg font-bold">Yang sudah diterima</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="photos">
          <div className="grid grid-cols-3 gap-4">
            <img
              src="/placeholder.svg"
              alt="Placeholder"
              width="100"
              height="100"
              style={{ aspectRatio: "100/100", objectFit: "cover" }}
            />
            <img
              src="/placeholder.svg"
              alt="Placeholder"
              width="100"
              height="100"
              style={{ aspectRatio: "100/100", objectFit: "cover" }}
            />
            <img
              src="/placeholder.svg"
              alt="Placeholder"
              width="100"
              height="100"
              style={{ aspectRatio: "100/100", objectFit: "cover" }}
            />
          </div>
        </TabsContent>
        <TabsContent value="posts">
          <Card>
            <CardContent>
              <h2 className="text-lg font-bold">Latest Post</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </main>
  )
}
